services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontendA
    ports:
      - "5173:5173"
    networks:
      - proyekTA

networks:
  proyekTA:
    external: true